# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.main_layout = QtWidgets.QHBoxLayout(MainWindow)
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setContentsMargins(0, 40, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.stackedWidget = PopUpAniStackedWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.page_1.sizePolicy().hasHeightForWidth())
        self.page_1.setSizePolicy(sizePolicy)
        self.page_1.setStyleSheet("")
        self.page_1.setObjectName("page_1")
        self.layoutWidget = QtWidgets.QWidget(self.page_1)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 450, 691, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SubtitleLabel = SubtitleLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubtitleLabel.sizePolicy().hasHeightForWidth())
        self.SubtitleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.SubtitleLabel.setFont(font)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayout.addWidget(self.SubtitleLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.merge_text = LineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.merge_text.sizePolicy().hasHeightForWidth())
        self.merge_text.setSizePolicy(sizePolicy)
        self.merge_text.setObjectName("merge_text")
        self.horizontalLayout.addWidget(self.merge_text)
        self.pushButton_5 = PushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_1 = PushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout.addWidget(self.pushButton_1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.page_1)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 56, 691, 35))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = PushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_4 = PushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.CardWidget = CardWidget(self.page_1)
        self.CardWidget.setGeometry(QtCore.QRect(30, 98, 691, 344))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget.sizePolicy().hasHeightForWidth())
        self.CardWidget.setSizePolicy(sizePolicy)
        self.CardWidget.setFrameShape(QtWidgets.QFrame.HLine)
        self.CardWidget.setObjectName("CardWidget")
        self.TableWidget = TableWidget(self.CardWidget)
        self.TableWidget.setEnabled(True)
        self.TableWidget.setGeometry(QtCore.QRect(10, 20, 681, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget.sizePolicy().hasHeightForWidth())
        self.TableWidget.setSizePolicy(sizePolicy)
        self.TableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TableWidget.setAutoFillBackground(True)
        self.TableWidget.setStyleSheet("QTableView {\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"}\n"
"\n"
"QTableView[isBorderVisible=true] {\n"
"    border: 1px solid rgb(0, 0, 12);\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 16px;\n"
"    padding-right: 16px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"QTableView::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"QHeaderView {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: transparent;\n"
"    color: rgb(96, 96, 96);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 15);\n"
"    font: 13px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    border-left: none;\n"
"    height: 33px;\n"
"}\n"
"\n"
"QTableView[isBorderVisible=true] QHeaderView::section:horizontal {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal:last {\n"
"    border-right: none;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Down_black.svg);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Up_black.svg);\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 15);\n"
"}\n"
"\n"
"QTableCornerButton::section:pressed {\n"
"    background-color: rgba(0, 0, 0, 12);\n"
"}")
        self.TableWidget.setLineWidth(1)
        self.TableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TableWidget.setRowCount(0)
        self.TableWidget.setSelectRightClickedRow(False)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(3, item)
        self.TableWidget.horizontalHeader().setVisible(True)
        self.TableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.TableWidget.horizontalHeader().setDefaultSectionSize(165)
        self.TableWidget.horizontalHeader().setHighlightSections(False)
        self.TableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.TableWidget.verticalHeader().setVisible(False)
        self.TableWidget.verticalHeader().setDefaultSectionSize(40)
        self.TitleLabel = TitleLabel(self.page_1)
        self.TitleLabel.setGeometry(QtCore.QRect(21, 11, 112, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleLabel.sizePolicy().hasHeightForWidth())
        self.TitleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("")
        self.page_2.setObjectName("page_2")
        self.CardWidget_2 = CardWidget(self.page_2)
        self.CardWidget_2.setGeometry(QtCore.QRect(30, 70, 711, 121))
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.CardWidget_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 11, 691, 100))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SubtitleLabel_3 = SubtitleLabel(self.layoutWidget2)
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.verticalLayout_5.addWidget(self.SubtitleLabel_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LineEdit_3 = LineEdit(self.layoutWidget2)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.horizontalLayout_4.addWidget(self.LineEdit_3)
        self.pushButton_2 = PushButton(self.layoutWidget2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.BodyLabel_3 = BodyLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_3.sizePolicy().hasHeightForWidth())
        self.BodyLabel_3.setSizePolicy(sizePolicy)
        self.BodyLabel_3.setTextFormat(QtCore.Qt.AutoText)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.verticalLayout_5.addWidget(self.BodyLabel_3)
        self.TitleLabel_2 = TitleLabel(self.page_2)
        self.TitleLabel_2.setGeometry(QtCore.QRect(20, 10, 123, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel_2.setFont(font)
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.CardWidget_5 = CardWidget(self.page_2)
        self.CardWidget_5.setGeometry(QtCore.QRect(30, 210, 711, 91))
        self.CardWidget_5.setObjectName("CardWidget_5")
        self.layoutWidget_5 = QtWidgets.QWidget(self.CardWidget_5)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 10, 691, 73))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.SubtitleLabel_4 = SubtitleLabel(self.layoutWidget_5)
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.verticalLayout_6.addWidget(self.SubtitleLabel_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LineEdit_7 = LineEdit(self.layoutWidget_5)
        self.LineEdit_7.setObjectName("LineEdit_7")
        self.horizontalLayout_5.addWidget(self.LineEdit_7)
        self.pushButton_3 = PushButton(self.layoutWidget_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.CardWidget_6 = CardWidget(self.page_2)
        self.CardWidget_6.setGeometry(QtCore.QRect(30, 320, 711, 151))
        self.CardWidget_6.setObjectName("CardWidget_6")
        self.layoutWidget3 = QtWidgets.QWidget(self.CardWidget_6)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 691, 131))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SubtitleLabel_5 = SubtitleLabel(self.layoutWidget3)
        self.SubtitleLabel_5.setObjectName("SubtitleLabel_5")
        self.verticalLayout_7.addWidget(self.SubtitleLabel_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.LineEdit_8 = LineEdit(self.layoutWidget3)
        self.LineEdit_8.setObjectName("LineEdit_8")
        self.horizontalLayout_11.addWidget(self.LineEdit_8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.BodyLabel = BodyLabel(self.layoutWidget3)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout_8.addWidget(self.BodyLabel)
        self.BodyLabel_2 = BodyLabel(self.layoutWidget3)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.verticalLayout_8.addWidget(self.BodyLabel_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.pushButton_7 = PushButton(self.page_2)
        self.pushButton_7.setGeometry(QtCore.QRect(610, 500, 131, 33))
        self.pushButton_7.setObjectName("pushButton_7")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.TitleLabel_5 = TitleLabel(self.page_3)
        self.TitleLabel_5.setGeometry(QtCore.QRect(20, 10, 123, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel_5.setFont(font)
        self.TitleLabel_5.setObjectName("TitleLabel_5")
        self.pushButton_9 = PushButton(self.page_3)
        self.pushButton_9.setGeometry(QtCore.QRect(610, 500, 131, 33))
        self.pushButton_9.setObjectName("pushButton_9")
        self.CardWidget_9 = CardWidget(self.page_3)
        self.CardWidget_9.setGeometry(QtCore.QRect(30, 220, 711, 91))
        self.CardWidget_9.setObjectName("CardWidget_9")
        self.layoutWidget_8 = QtWidgets.QWidget(self.CardWidget_9)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 10, 691, 73))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.SubtitleLabel_9 = SubtitleLabel(self.layoutWidget_8)
        self.SubtitleLabel_9.setObjectName("SubtitleLabel_9")
        self.verticalLayout_15.addWidget(self.SubtitleLabel_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.LineEdit_11 = LineEdit(self.layoutWidget_8)
        self.LineEdit_11.setObjectName("LineEdit_11")
        self.horizontalLayout_13.addWidget(self.LineEdit_11)
        self.pushButton_6 = PushButton(self.layoutWidget_8)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_13.addWidget(self.pushButton_6)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.CardWidget_10 = CardWidget(self.page_3)
        self.CardWidget_10.setGeometry(QtCore.QRect(30, 340, 711, 131))
        self.CardWidget_10.setObjectName("CardWidget_10")
        self.layoutWidget_9 = QtWidgets.QWidget(self.CardWidget_10)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 10, 691, 111))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.SubtitleLabel_10 = SubtitleLabel(self.layoutWidget_9)
        self.SubtitleLabel_10.setObjectName("SubtitleLabel_10")
        self.verticalLayout_17.addWidget(self.SubtitleLabel_10)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.LineEdit_12 = LineEdit(self.layoutWidget_9)
        self.LineEdit_12.setObjectName("LineEdit_12")
        self.horizontalLayout_14.addWidget(self.LineEdit_12)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.verticalLayout_16.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.BodyLabel_7 = BodyLabel(self.layoutWidget_9)
        self.BodyLabel_7.setObjectName("BodyLabel_7")
        self.verticalLayout_18.addWidget(self.BodyLabel_7)
        self.verticalLayout_16.addLayout(self.verticalLayout_18)
        self.CardWidget_11 = CardWidget(self.page_3)
        self.CardWidget_11.setGeometry(QtCore.QRect(30, 70, 711, 121))
        self.CardWidget_11.setObjectName("CardWidget_11")
        self.layoutWidget_10 = QtWidgets.QWidget(self.CardWidget_11)
        self.layoutWidget_10.setGeometry(QtCore.QRect(10, 11, 691, 100))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.SubtitleLabel_11 = SubtitleLabel(self.layoutWidget_10)
        self.SubtitleLabel_11.setObjectName("SubtitleLabel_11")
        self.verticalLayout_19.addWidget(self.SubtitleLabel_11)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.LineEdit_5 = LineEdit(self.layoutWidget_10)
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.horizontalLayout_15.addWidget(self.LineEdit_5)
        self.pushButton_10 = PushButton(self.layoutWidget_10)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_15.addWidget(self.pushButton_10)
        self.verticalLayout_19.addLayout(self.horizontalLayout_15)
        self.BodyLabel_9 = BodyLabel(self.layoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_9.sizePolicy().hasHeightForWidth())
        self.BodyLabel_9.setSizePolicy(sizePolicy)
        self.BodyLabel_9.setTextFormat(QtCore.Qt.AutoText)
        self.BodyLabel_9.setObjectName("BodyLabel_9")
        self.verticalLayout_19.addWidget(self.BodyLabel_9)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.CardWidget_12 = CardWidget(self.page_4)
        self.CardWidget_12.setGeometry(QtCore.QRect(30, 340, 711, 131))
        self.CardWidget_12.setObjectName("CardWidget_12")
        self.layoutWidget_11 = QtWidgets.QWidget(self.CardWidget_12)
        self.layoutWidget_11.setGeometry(QtCore.QRect(10, 10, 691, 111))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.SubtitleLabel_12 = SubtitleLabel(self.layoutWidget_11)
        self.SubtitleLabel_12.setObjectName("SubtitleLabel_12")
        self.verticalLayout_21.addWidget(self.SubtitleLabel_12)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.LineEdit_13 = LineEdit(self.layoutWidget_11)
        self.LineEdit_13.setObjectName("LineEdit_13")
        self.horizontalLayout_16.addWidget(self.LineEdit_13)
        self.verticalLayout_21.addLayout(self.horizontalLayout_16)
        self.verticalLayout_20.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.BodyLabel_8 = BodyLabel(self.layoutWidget_11)
        self.BodyLabel_8.setObjectName("BodyLabel_8")
        self.verticalLayout_22.addWidget(self.BodyLabel_8)
        self.verticalLayout_20.addLayout(self.verticalLayout_22)
        self.pushButton_11 = PushButton(self.page_4)
        self.pushButton_11.setGeometry(QtCore.QRect(610, 500, 131, 33))
        self.pushButton_11.setObjectName("pushButton_11")
        self.CardWidget_13 = CardWidget(self.page_4)
        self.CardWidget_13.setGeometry(QtCore.QRect(30, 70, 711, 121))
        self.CardWidget_13.setObjectName("CardWidget_13")
        self.layoutWidget_12 = QtWidgets.QWidget(self.CardWidget_13)
        self.layoutWidget_12.setGeometry(QtCore.QRect(10, 11, 691, 100))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.SubtitleLabel_13 = SubtitleLabel(self.layoutWidget_12)
        self.SubtitleLabel_13.setObjectName("SubtitleLabel_13")
        self.verticalLayout_23.addWidget(self.SubtitleLabel_13)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.LineEdit_6 = LineEdit(self.layoutWidget_12)
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.horizontalLayout_17.addWidget(self.LineEdit_6)
        self.pushButton_12 = PushButton(self.layoutWidget_12)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_17.addWidget(self.pushButton_12)
        self.verticalLayout_23.addLayout(self.horizontalLayout_17)
        self.BodyLabel_10 = BodyLabel(self.layoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BodyLabel_10.sizePolicy().hasHeightForWidth())
        self.BodyLabel_10.setSizePolicy(sizePolicy)
        self.BodyLabel_10.setTextFormat(QtCore.Qt.AutoText)
        self.BodyLabel_10.setObjectName("BodyLabel_10")
        self.verticalLayout_23.addWidget(self.BodyLabel_10)
        self.TitleLabel_6 = TitleLabel(self.page_4)
        self.TitleLabel_6.setGeometry(QtCore.QRect(20, 10, 151, 38))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel_6.setFont(font)
        self.TitleLabel_6.setObjectName("TitleLabel_6")
        self.CardWidget_14 = CardWidget(self.page_4)
        self.CardWidget_14.setGeometry(QtCore.QRect(30, 220, 711, 91))
        self.CardWidget_14.setObjectName("CardWidget_14")
        self.layoutWidget_13 = QtWidgets.QWidget(self.CardWidget_14)
        self.layoutWidget_13.setGeometry(QtCore.QRect(10, 10, 691, 73))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.SubtitleLabel_14 = SubtitleLabel(self.layoutWidget_13)
        self.SubtitleLabel_14.setObjectName("SubtitleLabel_14")
        self.verticalLayout_24.addWidget(self.SubtitleLabel_14)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.LineEdit_14 = LineEdit(self.layoutWidget_13)
        self.LineEdit_14.setObjectName("LineEdit_14")
        self.horizontalLayout_18.addWidget(self.LineEdit_14)
        self.pushButton_13 = PushButton(self.layoutWidget_13)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_18.addWidget(self.pushButton_13)
        self.verticalLayout_24.addLayout(self.horizontalLayout_18)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.TitleLabel_3 = TitleLabel(self.page_5)
        self.TitleLabel_3.setGeometry(QtCore.QRect(21, 11, 151, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleLabel_3.sizePolicy().hasHeightForWidth())
        self.TitleLabel_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel_3.setFont(font)
        self.TitleLabel_3.setObjectName("TitleLabel_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 450, 691, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SubtitleLabel_2 = SubtitleLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubtitleLabel_2.sizePolicy().hasHeightForWidth())
        self.SubtitleLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.SubtitleLabel_2.setFont(font)
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.verticalLayout_2.addWidget(self.SubtitleLabel_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.merge_text_2 = LineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.merge_text_2.sizePolicy().hasHeightForWidth())
        self.merge_text_2.setSizePolicy(sizePolicy)
        self.merge_text_2.setObjectName("merge_text_2")
        self.horizontalLayout_6.addWidget(self.merge_text_2)
        self.pushButton_8 = PushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.pushButton_14 = PushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_6.addWidget(self.pushButton_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.layoutWidget_3 = QtWidgets.QWidget(self.page_5)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 56, 691, 35))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_15 = PushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_7.addWidget(self.pushButton_15)
        self.pushButton_16 = PushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_7.addWidget(self.pushButton_16)
        self.CardWidget_3 = CardWidget(self.page_5)
        self.CardWidget_3.setGeometry(QtCore.QRect(30, 98, 691, 344))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_3.sizePolicy().hasHeightForWidth())
        self.CardWidget_3.setSizePolicy(sizePolicy)
        self.CardWidget_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.TableWidget_2 = TableWidget(self.CardWidget_3)
        self.TableWidget_2.setEnabled(True)
        self.TableWidget_2.setGeometry(QtCore.QRect(10, 20, 681, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget_2.sizePolicy().hasHeightForWidth())
        self.TableWidget_2.setSizePolicy(sizePolicy)
        self.TableWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TableWidget_2.setAutoFillBackground(True)
        self.TableWidget_2.setStyleSheet("QTableView {\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"}\n"
"\n"
"QTableView[isBorderVisible=true] {\n"
"    border: 1px solid rgb(0, 0, 12);\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 16px;\n"
"    padding-right: 16px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"QTableView::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"QHeaderView {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: transparent;\n"
"    color: rgb(96, 96, 96);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 15);\n"
"    font: 13px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    border-left: none;\n"
"    height: 33px;\n"
"}\n"
"\n"
"QTableView[isBorderVisible=true] QHeaderView::section:horizontal {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal:last {\n"
"    border-right: none;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Down_black.svg);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Up_black.svg);\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 15);\n"
"}\n"
"\n"
"QTableCornerButton::section:pressed {\n"
"    background-color: rgba(0, 0, 0, 12);\n"
"}")
        self.TableWidget_2.setLineWidth(1)
        self.TableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TableWidget_2.setRowCount(0)
        self.TableWidget_2.setSelectRightClickedRow(False)
        self.TableWidget_2.setObjectName("TableWidget_2")
        self.TableWidget_2.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_2.setHorizontalHeaderItem(3, item)
        self.TableWidget_2.horizontalHeader().setVisible(True)
        self.TableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.TableWidget_2.horizontalHeader().setDefaultSectionSize(165)
        self.TableWidget_2.horizontalHeader().setHighlightSections(False)
        self.TableWidget_2.horizontalHeader().setMinimumSectionSize(30)
        self.TableWidget_2.verticalHeader().setVisible(False)
        self.TableWidget_2.verticalHeader().setDefaultSectionSize(40)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.layoutWidget_4 = QtWidgets.QWidget(self.page_6)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 454, 691, 71))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SubtitleLabel_6 = SubtitleLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubtitleLabel_6.sizePolicy().hasHeightForWidth())
        self.SubtitleLabel_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.SubtitleLabel_6.setFont(font)
        self.SubtitleLabel_6.setObjectName("SubtitleLabel_6")
        self.verticalLayout_3.addWidget(self.SubtitleLabel_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.merge_text_3 = LineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.merge_text_3.sizePolicy().hasHeightForWidth())
        self.merge_text_3.setSizePolicy(sizePolicy)
        self.merge_text_3.setObjectName("merge_text_3")
        self.horizontalLayout_8.addWidget(self.merge_text_3)
        self.pushButton_17 = PushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_8.addWidget(self.pushButton_17)
        self.pushButton_18 = PushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_8.addWidget(self.pushButton_18)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.TitleLabel_4 = TitleLabel(self.page_6)
        self.TitleLabel_4.setGeometry(QtCore.QRect(21, 12, 181, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleLabel_4.sizePolicy().hasHeightForWidth())
        self.TitleLabel_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel_4.setFont(font)
        self.TitleLabel_4.setObjectName("TitleLabel_4")
        self.layoutWidget_6 = QtWidgets.QWidget(self.page_6)
        self.layoutWidget_6.setGeometry(QtCore.QRect(30, 60, 691, 35))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_19 = PushButton(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_9.addWidget(self.pushButton_19)
        self.pushButton_20 = PushButton(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_9.addWidget(self.pushButton_20)
        self.CardWidget_4 = CardWidget(self.page_6)
        self.CardWidget_4.setGeometry(QtCore.QRect(30, 102, 691, 344))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_4.sizePolicy().hasHeightForWidth())
        self.CardWidget_4.setSizePolicy(sizePolicy)
        self.CardWidget_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.TableWidget_3 = TableWidget(self.CardWidget_4)
        self.TableWidget_3.setEnabled(True)
        self.TableWidget_3.setGeometry(QtCore.QRect(10, 20, 681, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget_3.sizePolicy().hasHeightForWidth())
        self.TableWidget_3.setSizePolicy(sizePolicy)
        self.TableWidget_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TableWidget_3.setAutoFillBackground(True)
        self.TableWidget_3.setStyleSheet("QTableView {\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"}\n"
"\n"
"QTableView[isBorderVisible=true] {\n"
"    border: 1px solid rgb(0, 0, 12);\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 16px;\n"
"    padding-right: 16px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"QTableView::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"QHeaderView {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: transparent;\n"
"    color: rgb(96, 96, 96);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 15);\n"
"    font: 13px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    border-left: none;\n"
"    height: 33px;\n"
"}\n"
"\n"
"QTableView[isBorderVisible=true] QHeaderView::section:horizontal {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal:last {\n"
"    border-right: none;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Down_black.svg);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Up_black.svg);\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 15);\n"
"}\n"
"\n"
"QTableCornerButton::section:pressed {\n"
"    background-color: rgba(0, 0, 0, 12);\n"
"}")
        self.TableWidget_3.setLineWidth(1)
        self.TableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TableWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TableWidget_3.setRowCount(0)
        self.TableWidget_3.setSelectRightClickedRow(False)
        self.TableWidget_3.setObjectName("TableWidget_3")
        self.TableWidget_3.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_3.setHorizontalHeaderItem(3, item)
        self.TableWidget_3.horizontalHeader().setVisible(True)
        self.TableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.TableWidget_3.horizontalHeader().setDefaultSectionSize(165)
        self.TableWidget_3.horizontalHeader().setHighlightSections(False)
        self.TableWidget_3.horizontalHeader().setMinimumSectionSize(30)
        self.TableWidget_3.verticalHeader().setVisible(False)
        self.TableWidget_3.verticalHeader().setDefaultSectionSize(40)
        self.stackedWidget.addWidget(self.page_6)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.setting_page)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setting_layout = QtWidgets.QVBoxLayout()
        self.setting_layout.setSpacing(0)
        self.setting_layout.setObjectName("setting_layout")
        self.horizontalLayout_2.addLayout(self.setting_layout)
        self.stackedWidget.addWidget(self.setting_page)
        self.main_layout.addWidget(self.stackedWidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "简易PDF工具箱"))
        self.SubtitleLabel.setText(_translate("MainWindow", "生成文件路径"))
        self.pushButton_5.setText(_translate("MainWindow", "选择目录"))
        self.pushButton_1.setText(_translate("MainWindow", "生成文件"))
        self.pushButton.setText(_translate("MainWindow", "导入文件"))
        self.pushButton_4.setText(_translate("MainWindow", "删除文件"))
        self.TableWidget.setSortingEnabled(False)
        item = self.TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "源文件名"))
        item = self.TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "页数"))
        item = self.TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "文件位置"))
        item = self.TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "修改时间"))
        self.TitleLabel.setText(_translate("MainWindow", "合并文档"))
        self.SubtitleLabel_3.setText(_translate("MainWindow", "导入源文件"))
        self.pushButton_2.setText(_translate("MainWindow", "浏览"))
        self.BodyLabel_3.setText(_translate("MainWindow", "文件总页数："))
        self.TitleLabel_2.setText(_translate("MainWindow", "拆分文档"))
        self.SubtitleLabel_4.setText(_translate("MainWindow", "输出文件路径"))
        self.pushButton_3.setText(_translate("MainWindow", "浏览"))
        self.SubtitleLabel_5.setText(_translate("MainWindow", "需要拆分的页码"))
        self.BodyLabel.setText(_translate("MainWindow", "格式形如：1-5,7;9-10;8-11,13"))
        self.BodyLabel_2.setText(_translate("MainWindow", "以分号相隔的部分会被视为两个文件"))
        self.pushButton_7.setText(_translate("MainWindow", "导出文件"))
        self.TitleLabel_5.setText(_translate("MainWindow", "删除页面"))
        self.pushButton_9.setText(_translate("MainWindow", "导出文件"))
        self.SubtitleLabel_9.setText(_translate("MainWindow", "输出文件路径"))
        self.pushButton_6.setText(_translate("MainWindow", "浏览"))
        self.SubtitleLabel_10.setText(_translate("MainWindow", "需要删除的页码"))
        self.BodyLabel_7.setText(_translate("MainWindow", "格式形如：1-5,7,9-10,13"))
        self.SubtitleLabel_11.setText(_translate("MainWindow", "导入源文件"))
        self.pushButton_10.setText(_translate("MainWindow", "浏览"))
        self.BodyLabel_9.setText(_translate("MainWindow", "文件总页数："))
        self.SubtitleLabel_12.setText(_translate("MainWindow", "需要转换的页码"))
        self.BodyLabel_8.setText(_translate("MainWindow", "格式形如：1-5,7,9-10,13"))
        self.pushButton_11.setText(_translate("MainWindow", "导出文件"))
        self.SubtitleLabel_13.setText(_translate("MainWindow", "导入源文件"))
        self.pushButton_12.setText(_translate("MainWindow", "浏览"))
        self.BodyLabel_10.setText(_translate("MainWindow", "文件总页数："))
        self.TitleLabel_6.setText(_translate("MainWindow", "PDF转图片"))
        self.SubtitleLabel_14.setText(_translate("MainWindow", "输出文件路径"))
        self.pushButton_13.setText(_translate("MainWindow", "浏览"))
        self.TitleLabel_3.setText(_translate("MainWindow", "图片转PDF"))
        self.SubtitleLabel_2.setText(_translate("MainWindow", "生成文件路径"))
        self.pushButton_8.setText(_translate("MainWindow", "选择目录"))
        self.pushButton_14.setText(_translate("MainWindow", "生成文件"))
        self.pushButton_15.setText(_translate("MainWindow", "导入图片"))
        self.pushButton_16.setText(_translate("MainWindow", "删除图片"))
        self.TableWidget_2.setSortingEnabled(False)
        item = self.TableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "源文件名"))
        item = self.TableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "尺寸"))
        item = self.TableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "文件位置"))
        item = self.TableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "修改时间"))
        self.SubtitleLabel_6.setText(_translate("MainWindow", "生成文件路径"))
        self.pushButton_17.setText(_translate("MainWindow", "选择目录"))
        self.pushButton_18.setText(_translate("MainWindow", "生成文件"))
        self.TitleLabel_4.setText(_translate("MainWindow", "WORD转PDF"))
        self.pushButton_19.setText(_translate("MainWindow", "导入文件"))
        self.pushButton_20.setText(_translate("MainWindow", "删除文件"))
        self.TableWidget_3.setSortingEnabled(False)
        item = self.TableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "源文件名"))
        item = self.TableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文件大小"))
        item = self.TableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "文件位置"))
        item = self.TableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "修改时间"))
from qfluentwidgets import BodyLabel, CardWidget, LineEdit, PopUpAniStackedWidget, PushButton, SubtitleLabel, TableWidget, TitleLabel
import resource_rc
